### ISSUE TITLE
Documenting issues on UWP

### ISSUE THREAD

**Issue by charlesroddie** [FoggyFinder/FSharpCoreRtTest#1]
As per Don's [comment](https://github.com/dotnet/corert/issues/5780#issuecomment-400400677) we need to document what doesn't work in .Net Native.

We encontered 3 types of issue:

- sprintf and .ToString() : sprintf doesn't work unaided, and .ToString() doesn't work on records and DUs. Is there a way to get sprintf working on primitive types using rd.xml ?
- Serialization: Many types seem to work even without rd.xml, even records and DUs, but we need to clarify which types work and which types don't, and for the types that don't check that rd.xml works as normal.
- Converting F# functions to LINQ expressions.

A good format is for a piece of evidence to be accompanied by code showing it working (if it works) or commented out code which breaks if uncommented (if it doesn't work).

- [x] Document sprintf and .ToString()
- [x] Document serialization
- [x] Document LINQ

**Comment by charlesroddie** [comment]
@FoggyFinder I think it would make sense to put all code relevant to testing this on a single new branch but it's up to you if you prefer to do it differently.

Any help appreciated @nbevans @zpodlovics @DjArt .

**Comment by FoggyFinder** [comment]
> I think it would make sense to do all the documentation on a single new branch but it's up to you if you prefer to do it differently.

Maybe better to put this information to ReadMe?

**Comment by charlesroddie** [comment]
Yes information can go into a readme. Sorry I meant the code that shows things working and not working.

**Comment by FoggyFinder** [comment]
Okay, I tried to summarize information. So it looks like the main problem is frequent using of `MakeGenericType/MakeGenericMethod` in `FSharp.Core`.
